import { Container } from '@mui/material';
import Grid2 from '@mui/material/Unstable_Grid2/Grid2'
import type { NextPage } from "next";
import Head from 'next/head'
import Header from '../components/header';
import MainPage from '../components/mainPage';



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <body>
        <Container>
          <Grid2>
            <Header />
          </Grid2>
          <Grid2>
            <MainPage />
          </Grid2>
        </Container>
        
      </body>
    </div>
  )
}

export default Home;
